getuto: XFAIL another fetch from keys.openpgp.org
We need to verify our UIDs on keys.openpgp.org.

```
+ gpg --no-permission-warning --batch --keyserver hkps://keys.openpgp.org --refresh-keys
gpg: refreshing 5 keys from hkps://keys.openpgp.org
gpg: key BB572E0E2D182910: no user ID
gpg: key 9E6438C817072058: no user ID
gpg: key DB6B8C1F96D8BF6D: no user ID
gpg: key A13D0EF1914E7A72: no user ID
gpg: Total number processed: 4
make: *** [Makefile:5: check] Error 2
Error: Process completed with exit code 2.
```

Signed-off-by: Sam James <sam@gentoo.org>